config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :superpowers, only: %i[index show new create destroy] do
    resources :bookings, only: %i[new create]
  end

  get '/my_superpowers', to: 'superpowers#my_superpowers'
  get '/my_superpowers/:id/edit', to: 'superpowers#edit', as: :edit_superpower
  patch '/my_superpowers/:id', to: 'superpowers#update', as: :update_superpower
  get '/my_superpowers/:id/toggle_availability', to: 'superpowers#toggle_availability', as: :toggle_availability

  resources :bookings, only: :show, as: :booking

  get '/my_bookings', to: 'bookings#my_bookings'
  get '/my_owner_bookings', to: 'bookings#my_owner_bookings'
  get '/bookings/:id/accept', to: 'bookings#accept', as: :accept_booking
  get '/bookings/:id/decline', to: 'bookings#decline', as: :decline_booking
  get '/bookings/:id/cancel', to: 'bookings#cancel', as: :cancel_booking
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  STATUSES = %w[accepted declined pending cancelled]

  belongs_to :user
  belongs_to :superpower

  validates :status, inclusion: { in: STATUSES }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates_comparison_of :start_date, greater_than_or_equal_to: Date.today
  validates_comparison_of :end_date, greater_than_or_equal_to: :start_date

  before_validation :set_to_pending_if_no_status

  private

  def set_to_pending_if_no_status
    self.status = status.nil? ? "pending" : status
  end
end

app/models/superpower.rb
class Superpower < ApplicationRecord
  CATEGORIES = %w[transformation superhuman elemental imperceptible others]

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :description, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  validates :price_per_day, presence: true, numericality: { only_integer: true, minimum: 1 }
  validates :address, presence: true
  validates :listed, inclusion: [true, false]

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :superpowers, dependent: :destroy
  has_many :bookings, dependent: :destroy

  validates :username, presence: true, uniqueness: true, length: { maximum: 15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_superpower, only: %i[new create]
  before_action :set_booking, only: %i[show accept decline cancel]

  def show
    @user_is_power_owner = @booking.user != current_user
    @total_price = ((@booking.end_date - @booking.start_date).to_i + 1) * @booking.superpower.price_per_day
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.superpower = @superpower
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new, status: 422
    end
  end

  def my_bookings
    @bookings = Booking.where(user: current_user).order(created_at: :desc)
  end

  def my_owner_bookings
    @bookings = Booking.where(superpower: current_user.superpowers).order(created_at: :desc)
  end

  def accept
    @booking.update(status: "accepted")
    redirect_to booking_path(@booking)
  end

  def decline
    @booking.update(status: "declined")
    redirect_to booking_path(@booking)
  end

  def cancel
    @booking.update(status: "cancelled")
    redirect_to booking_path(@booking)
  end

  private

  def set_superpower
    @superpower = Superpower.find(params[:superpower_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/superpowers_controller.rb
class SuperpowersController < ApplicationController
  skip_before_action :authenticate_user!, only: %w[index show]
  before_action :set_superpower, only: %w[show edit update destroy toggle_availability]

  def index
    if params[:q].present?
      sql_query = <<~SQL
        superpowers.name ILIKE :query
        OR superpowers.description ILIKE :query
        OR superpowers.address ILIKE :query
        OR superpowers.category ILIKE :query
      SQL
      @superpowers = Superpower.where(listed: true).where(sql_query, query: "%#{params[:q]}%").order(created_at: :desc)
    else
      @superpowers = Superpower.where(listed: true).order(created_at: :desc)
    end

    @markers = @superpowers.geocoded.map do |superpower|
      {
        lat: superpower.latitude,
        lng: superpower.longitude,
        info_window: render_to_string(partial: "info_window", locals: { superpower: superpower }),
        image_url: helpers.asset_url("pow.png")
      }
    end
  end

  def show
  end

  def new
    @superpower = Superpower.new
  end

  def create
    @superpower = Superpower.new(superpower_params)
    @superpower.user = current_user
    if @superpower.save
      redirect_to superpower_path(@superpower)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def destroy
    @superpower.destroy
    redirect_to my_superpowers_path, status: :see_other
  end

  def update
    if @superpower.update(superpower_params)
      redirect_to superpower_path(@superpower)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def my_superpowers
    @superpowers = Superpower.where(user: current_user).order(:created_at)
  end

  def toggle_availability
    if @superpower.listed
      @superpower.update(listed: false)
    else
      @superpower.update(listed: true)
    end
    redirect_to my_superpowers_path
  end

  private

  def set_superpower
    @superpower = Superpower.find(params[:id])
  end

  def superpower_params
    params.require(:superpower).permit(:name, :description, :category, :price_per_day, :listed, :photo, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form_booking.html.erb
<div class="form-container" data-controller="booking-form">
  <h3>Book <em><%= superpower.name %></em></h3>

  <%= simple_form_for [superpower, booking] do |f| %>
    <p>Price per day: $<%= superpower.price_per_day %></p>

    <%= f.input :start_date, start_year: Date.today.year, html5: true,
        input_html: {data: {action: "change->booking-form#changeTotal", booking_form_target: "start"}} %>

    <%= f.input :end_date, start_year: Date.today.year, html5: true,
        input_html: {data: {action: "change->booking-form#changeTotal", booking_form_target: "end"}} %>

    <%= f.input :price, as: :hidden,
        input_html: {value: "#{superpower.price_per_day}", data: {booking_form_target: "price"}} %>

    <p data-booking-form-target="total"></p>

    <%= f.submit "Book Now", class: "btn btn-warning" %>
  <% end %>
</div>

app/views/bookings/my_bookings.html.erb
<div class="container">
  <div class="top-spacer"></div>
    <h2 id="space-between" class="comic-header">Superpowers you've booked</h2>

    <div class="bookings-product">
      <% @bookings.each do |booking| %>
          <div class ="bookings-product-card <%= booking.superpower.category %>">

            <div class="image-card">
              <% if booking.superpower.photo.key %>
                <%= cl_image_tag booking.superpower.photo.key, height: 150, width: 150, crop: :fill %>
              <% else %>
                <%= image_tag "not_available.jpg", height: 150, width: 150 %>
              <% end %>
            </div>

            <div class="bookings-details-card">
              <p class="superpower-name"><%= link_to booking.superpower.name, booking_path(booking) %></p>
              <p class="booking-date"><%= booking.start_date %></p>
              <p class="booking-date"><%= booking.end_date %></p>
              <p class="booking-status"><%= booking.status.capitalize %></p>
            </div>
          </div>
      <% end %>
    </div>
</div>

app/views/bookings/my_owner_bookings.html.erb
<div class="container">
<div class="top-spacer"></div>
  <h2 id="space-between" class="comic-header">Superpowers you've rented out</h2>

  <div class="bookings-product">
    <% @bookings.each do |booking| %>
       <div class ="bookings-product-card <%= booking.superpower.category %>">

          <div class="image-card">
             <% if booking.superpower.photo.key %>
              <%= cl_image_tag booking.superpower.photo.key, height: 150, width: 150, crop: :fill %>
             <% else %>
               <%= image_tag "not_available.jpg", height: 150, width: 150 %>
            <% end %>
          </div>

      <div class="bookings-details-card">
        <p class="superpower-name"><%= link_to booking.superpower.name, booking_path(booking) %></p>
        <p class="booking-date"><%= booking.start_date %></p>
        <p class="booking-date"><%= booking.end_date %></p>
        <p class="booking-status"><%= booking.status.capitalize %></p>
      </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <%= render "form_booking", superpower: @superpower, booking: @booking %>

  <div class="form-footer">
    <%= link_to(superpower_path(@superpower)) do %>
      <i class="fa-solid fa-circle-left"></i> Back
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="top-spacer"></div>

  <h2 class="comic-header">Booking Details</h2>

  <div class="booking-info">
    <div class="superpower-card <%= @booking.superpower.category %>">
      <p><i class="fa-solid fa-burst"></i> <strong>Superpower booked</strong></p>
      <% if @booking.superpower.photo.key %>
        <%= cl_image_tag @booking.superpower.photo.key, height: 120, width: 200, crop: :fill %>
      <% else %>
        <%= image_tag "not_available.jpg", height: 120, width: 200 %>
      <% end %>
      <p class="superpower-name"><em><%= @booking.superpower.name %></em></p>
      <p class="superpower-description"><%= @booking.superpower.description %></p>
    </div>

    <div class="booking-details">
      <p>
        <strong>Superpower owner:</strong> <%= @booking.superpower.user.username %> (<%= @booking.superpower.user.email %>)<br>
        <strong>Superpower location:</strong> <%= @booking.superpower.address %><br>
        <strong>Booked by:</strong> <%= @booking.user.username %> (<%= @booking.user.email %>)<br>
        <strong>From:</strong> <%= @booking.start_date %><br>
        <strong>To:</strong> <%= @booking.end_date %><br>
        <strong>Total price:</strong> $<%= @total_price %><br>
        <strong>Current status:</strong> <%= @booking.status %>
      </p>

      <div class="booking-status-links">
        <% if @booking.status == "pending" %>
          <% if @user_is_power_owner %>
            <%= link_to(accept_booking_path(@booking), class: "accept-link") do %>
              <i class="fa-solid fa-circle-check"></i> Accept this booking
            <% end %>
            <br>
            <%= link_to(decline_booking_path(@booking), class: "decline-link") do %>
              <i class="fa-solid fa-circle-xmark"></i> Decline this booking
            <% end %>
          <% else %>
            <%= link_to(cancel_booking_path(@booking), class: "cancel-link") do %>
              <i class="fa-solid fa-rectangle-xmark"></i> Cancel this booking
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="back-link">
    <% if @user_is_power_owner %>
      <%= link_to(my_owner_bookings_path) do %>
        <i class="fa-solid fa-circle-left"></i> Back
      <% end %>
    <% else %>
      <%= link_to(my_bookings_path) do %>
        <i class="fa-solid fa-circle-left"></i> Back
      <% end %>
    <% end %>
  </div>
</div>

<%# "Created at: #{@booking.created_at.strftime("%A, %d %b %Y %l:%M %p")}"%>
<%# "Updated at: #{@booking.updated_at.strftime("%A, %d %b %Y %l:%M %p")}"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSuperpowersbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
    <div class="navbar-spacer"></div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/ahsanazim/slack-landing-page/master/screen_caps/main_background.jpg); height: 100vh">
  <div class="container">
    <h1 style= "color:#F7B538;">What's useless to you might not be for others...</h1>
    <p style= "color:#F7B538;">Discover and exchange superpowers to satisfy your current needs!</p>
    <div class="d-grid gap-2 col-6 mx-auto">
      <%= link_to "Explore your options", superpowers_path, class: "btn btn-outline-warning btn-lg" %>
    </div>
  </div>
</div>

<%# <h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p> %>
<%# background-repeat= "no-repeat" background-size="cover" %>
<%# <div class= "container-fluid" style= "padding: 0"> %>
<%# </div> %>

<%# <div class = "banner img-responsive" style="background-image: url(https://motionarray.imgix.net/preview-139726-4J4dBww3x8-high_0006.jpg?w=660&q=60&fit=max&auto=format); height: 100vh;"> %>
<%# <a class="btn btn-lg btn-outline-secondary fw bold border-white " href="#">Explore your options</a> %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <%# <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div> %>
  <div class="footer-copyright">
    Helloooooooo <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-custom fixed-top">
  <div class="container-fluid">
    <%= link_to(superpowers_path, class: "navbar-brand") do %>
      <i class="fa-solid fa-hand-fist"></i> OneForAll
    <% end %>

    <form action="/superpowers" class="d-flex">
      <input name="q" class="form-control me-2" type="search" placeholder="Find a superpower">
      <button id="search-button" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>

    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class= "navbar-nav">
        <li class="nav-item">
          <%= link_to "Add a Superpower", new_superpower_path, class: "nav-link-custom" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Superpowers", my_superpowers_path, class: "nav-link-custom" %>
        </li>
        <li class="nav-item">
          <%= link_to "Superpowers I've Booked", my_bookings_path, class: "nav-link-custom" %>
        </li>
        <li class="nav-item">
          <%= link_to "Superpowers I've Rented Out", my_owner_bookings_path, class: "nav-link-custom" %>
        </li>
      </ul>
    </div>

    <div class="ms-auto navbar-buttons">
      <% if user_signed_in? %>
        <p><em>Logged in as </em><strong><%= current_user.username %></strong></p>
        <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "btn btn-warning" %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "btn btn-warning" %>
        <%= link_to "Register", new_user_registration_path, class: "btn btn-warning" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/superpowers/_form_superpower.html.erb
<div class="form-container">
  <h3>Add a new superpower</h3>

  <%= simple_form_for(superpower) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.input :category, as: :select, collection: Superpower::CATEGORIES.map { |c| [c.capitalize, c] } %>
    <%= f.input :price_per_day %>
    <%= f.input :address, label: "Location", input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
        wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
    <%= f.input :listed, label: "For rent right now?", as: :radio_buttons, required: true %>
    <%= f.submit "Add Superpower", class: "btn btn-warning" %>
  <% end %>
</div>

app/views/superpowers/_info_window.html.erb
<div class="course">
    <div class="course-preview <%= superpower.category %>">
      <h6><%= superpower.address %></h6>
      <h3><%= superpower.category %></h3>
      <%= link_to 'View details', superpower_path(superpower), class:"fas fa-chevron-right" %>
    </div>
    <div class="course-info">
      <h6>Price per day: $<%= superpower.price_per_day %></h6>
      <h2><%= superpower.name %></h2>
       <%= link_to 'Book', superpower_path(superpower), :class => "btn-infobox-book #{superpower.category}" %>
    </div>
</div>

app/views/superpowers/edit.html.erb
<div class="container">
  <div class="form-container">
    <h3>Modify this superpower</h3>

    <%= simple_form_for(@superpower, url: update_superpower_path(@superpower)) do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :photo, as: :file %>
      <%= f.input :category, as: :select, collection: Superpower::CATEGORIES.map { |c| [c.capitalize, c] } %>
      <%= f.input :price_per_day %>
      <%= f.input :address, label: "Location", input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
          wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
      <%= f.submit class: "btn btn-warning" %>
    <% end %>
  </div>

  <div class="form-footer">
    <%= link_to(my_superpowers_path) do %>
      <i class="fa-solid fa-circle-left"></i> Back to my superpowers
    <% end %>
  </div>
</div>

app/views/superpowers/index.html.erb
<div class="main-container">
  <div class="container">
    <h1 id="index-title" class="comic-header">List of Superpowers 💥💫</h1>

    <div class="cards">
      <% @superpowers.each do |superpower| %>
      <div class="card-trip <%= superpower.category %>">
        <% if superpower.photo.key %>
          <%= cl_image_tag superpower.photo.key, height: 200 %>
        <% else %>
          <%= image_tag "not_available.jpg", height: 200 %>
        <% end %>
        <div class="card-trip-infos">
          <div>
            <%= link_to superpower.name, superpower_path(superpower), class: "btn-flat" %>
            <p>Category: <%= superpower.category.capitalize %></p>
          </div>
            <h3 class="card-trip-pricing"><%= superpower.price_per_day %></h3>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div id="map"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/superpowers/my_superpowers.html.erb
<div class="container">
  <div class="top-spacer"></div>
    <h2 id="space-between" class="comic-header">My Superpowers</h2>

    <div class="superpowers-product">
      <% @superpowers.each do |superpower| %>
        <div class ="superpowers-product-card <%= superpower.category %>">

          <div class="image-card">
            <% if superpower.photo.key %>
              <%= cl_image_tag superpower.photo.key, height: 150, width: 150, crop: :fill %>
            <% else %>
              <%= image_tag "not_available.jpg", height: 150, width: 150 %>
            <% end %>
          </div>

          <div class="superpowers-details-card">
            <p class="superpower-name"><%= link_to superpower.name, superpower_path(superpower) %></p>
            <p class="superpower-category"><%= superpower.category.capitalize %></p>
            <p class="superpower-price"><%= superpower.price_per_day %></p>

            <div class="card-links">
            <%= link_to(toggle_availability_path(superpower)) do %>
              <% if superpower.listed %>
                <i class="fa-solid fa-square-check"></i> Listed
              <% else %>
                <i class="fa-solid fa-square-xmark"></i> Unlisted
              <% end %>
            <% end %>

            <%= link_to(edit_superpower_path(superpower)) do %>
              <i class="fa-solid fa-square-pen"></i>
            <% end %>

            <%= link_to(superpower_path(superpower), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} ) do %>
              <i class="fa-solid fa-square-minus"></i>
            <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  <div class="back-link mt-4">
    <%= link_to(superpowers_path) do %>
      <i class="fa-solid fa-circle-left"></i> Back to index
    <% end %>
  </div>
</div>

app/views/superpowers/new.html.erb
<div class="container">
  <%= render "form_superpower", superpower: @superpower %>

  <div class="form-footer">
    <%= link_to(superpowers_path) do %>
      <i class="fa-solid fa-circle-left"></i> Back
    <% end %>
  </div>
</div>

app/views/superpowers/show.html.erb
 <%# will be changed later, just need to put something here %>

<div class="container container-custom">
  <div class="single-power">
    <div class="row">
      <div class="col-6">
        <div class="power-image">
          <div class="power-image-main">
            <% if @superpower.photo.key %>
              <%= cl_image_tag @superpower.photo.key, height: 480, width: 570, crop: :fill %>
            <% else %>
              <%= image_tag "not_available.jpg", height: 480, width: 570 %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class="breadcrumb">
          <span><%= link_to "Back to index", superpowers_path %></span>
        </div>

        <div class="power">
          <div class="power-name">
            <h2><%= @superpower.name %></h2>
            <h3><%= @superpower.category.capitalize %></h3>
          </div>
          <div class="power-price">
            <span class="offer-price"><strong>$<%= @superpower.price_per_day %></strong></span>
          </div>

          <div class="power-details">
            <h4>Description</h4>
            <p><%= @superpower.description %></p>
          </div>
          <span class="divider"></span>

          <div class="power-btn-select">
            <% if @superpower.user == current_user %>
              <div><%= link_to "Edit this superpower", edit_superpower_path(@superpower), class: "btn btn-dark" %></div>
            <% else %>
              <div><%= link_to "Book this superpower", new_superpower_booking_path(@superpower), class: "btn btn-dark" %></div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>